services:
  app-westiti:
    container_name: app-westiti
    build:
      context: ./App
      dockerfile: dockerfile.dev
    volumes:
      - ./App:/usr/src/app
      - /usr/src/app/node_modules/
    env_file:
      - .env    
    ports:
      - "5173:5173"
    networks:
      - westiti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-westiti.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app-westiti.entrypoints=web"
      - "traefik.http.services.app-westiti.loadbalancer.server.port=5173"

  api-westiti:
    container_name: api-westiti
    build:
      context: ./Api
      dockerfile: dockerfile.dev
    volumes:
      - ./Api:/usr/src/api
      - /usr/src/api/node_modules/
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - westiti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-westiti.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api-westiti.entrypoints=web"
      - "traefik.http.services.api-westiti.loadbalancer.server.port=3000"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: always
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"  # HTTP seulement
      - "8080:8080"  # Dashboard Traefik (optionnel)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - westiti
  postgres-westiti:
    container_name: postgres-westiti
    image: postgres:latest
    restart: always 
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - westiti
  
networks:
  westiti:
    driver: bridge