FROM node:20-alpine

WORKDIR /usr/src/App

COPY package*.json .

# RUN npm ci --only=production

COPY . .

# RUN npm run build

# FROM node:20-alpine

RUN npm install i

# WORKDIR /usr/src/App

# COPY --from=builder /usr/src/App/dist ./dist

EXPOSE 5173

CMD ["npm", "run", "dev"]