# Étape 1 : Builder l'application
FROM node:20-alpine AS builder

# Définir le répertoire de travail
WORKDIR /usr/src/App

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Construire l'application
RUN npm run build

# Étape 2 : Créer l'image finale avec les fichiers construits
FROM node:20-alpine

# Définir le répertoire de travail pour le serveur
WORKDIR /usr/src/App

# Installer le serveur serve
RUN npm install -g serve

# Copier les fichiers construits depuis l'étape précédente
COPY --from=builder /usr/src/App/dist ./dist

# Exposer le port
EXPOSE 4173

# Démarrer l'application avec serve
CMD ["serve", "-l", "4173", "-s", "dist"]
