FROM node:20

WORKDIR /usr/src/App
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
COPY package*.json .

# RUN npm ci --only=production

COPY . .

# RUN npm run build

# FROM node:20-alpine

RUN npm i --only=development

# WORKDIR /usr/src/App

# COPY --from=builder /usr/src/App/dist ./dist

EXPOSE 5173

CMD ["npm", "run", "dev"]