FROM node:20-alpine

WORKDIR /usr/src/frontOffice

COPY ./package*.json ./

# RUN npm install -g pm2
RUN npm install 

COPY . .

EXPOSE 5173
#EXPOSE 4173

# RUN npm run build

# CMD ["pm2", "serve", "./dist", "--name", "app", "--spa", "--port", "4173"]

# RUN npm install -g http-server
# CMD ["http-server", "dist", "-p", "4173", "-P", "/"]

CMD ["npm", "run", "dev", "--host"]