FROM node:20 AS base

WORKDIR /usr/src/api
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
COPY package*.json ./

# RUN apk update && apk add openssl

RUN npm i --only=development

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]