FROM node:20-alpine as base

WORKDIR /usr/src/frontOffice

COPY package*.json ./

RUN apk update && apk add openssl

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
